
export const ADD_SHOW_DATABASE = 'ADD_SHOW_DATABASE';
export const ADD_SHOW_USER = 'ADD_SHOW_USER';
export const REMOVE_SHOW_USER = 'REMOVE_SHOW_USER';
export const ADD_NEW_USER = 'ADD_NEW_USER';
export const ADD_SHOW_REQUESTED = 'ADD_SHOW_REQUESTED';
export const ADD_SHOW_REJECTED = 'ADD_SHOW_REJECTED';
export const ADD_SHOW_FULFILLED = 'ADD_SHOW_FULFILLED';
export const GET_USER_DATA_REQUESTED = 'GET_USER_DATA_REQUESTED';
export const GET_USER_DATA_REJECTED = 'GET_USER_DATA_REJECTED';
export const GET_USER_DATA_FULFILLED = 'GET_USER_DATA_FULFILLED';
